const en = {
  label: "English",
  dir: "ltr",
  nav: {
    home: "Home",
    about: "About the Project",
    van: "Milk Bank Van",
    partners: "Partners",
    support: "Support the Cause",
    faqs: "FAQs",
    contact: "Contact",
    menu: "Menu",
    close: "Close",
  },
  cta: {
    donor: "Become a Milk Donor",
    support: "Support the Cause",
    learnProject: "Learn About the Project",
    exploreVan: "Explore the Milk Bank Van",
    meetPartners: "Meet Our Partners",
    readFaqs: "Read FAQs",
    viewAllFaqs: "View All FAQs",
    contact: "Contact Us",
    home: "Return to Home",
    partnerWith: "Partner With the Initiative",
    exploreSupport: "Explore Support & Partnership",
    explorePartnership: "Explore Partnership Opportunities",
    exploreWays: "Explore Ways to Support",
    visitFaqs: "Visit FAQs",
    register: "Register My Interest",
    sendEnquiry: "Send Enquiry",
    sendSupport: "Send Support Enquiry",
    needHelp: "Need Help?",
    talkToTeam: "Talk to Our Team",
  },
  grant: {
    badge: "A Rotary Global Grant Project",
    number: "Global Grant No. GG2694832",
  },
  footer: {
    desc: "Maa Yashoda is a breastfeeding awareness, human milk donation and Human Milk Bank outreach initiative supported by Rotary organizations, healthcare institutions, implementation partners and the community in Surat.",
    explore: "Explore",
    getInvolved: "Get Involved",
    help: "Help",
    legal: "Legal",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    accessibility: "Accessibility Statement",
    copyright: "© 2026 Maa Yashoda. All rights reserved.",
    note: "Content on this website is intended for general awareness and is not a substitute for professional medical advice.",
  },
  form: {
    required: "Required",
    optionalLabel: "Optional",
    fullName: "Full Name",
    mobile: "Mobile Number",
    email: "Email Address",
    city: "City / Area",
    state: "State",
    org: "Organization Name",
    designation: "Designation",
    message: "Message",
    describeYou: "Which best describes you?",
    contactMethod: "Preferred Contact Method",
    phone: "Phone",
    whatsapp: "WhatsApp",
    additional: "Additional Message",
    select: "Please select",
    interestOptions: [
      "I would like to learn more about milk donation",
      "I am interested in becoming a potential milk donor",
      "I would like guidance through the process",
      "Other",
    ],
    consentVoluntary:
      "I confirm that I am voluntarily registering my interest to learn more about the possibility of milk donation.",
    consentContact: "I consent to being contacted regarding my registration and the next steps.",
    consentGeneral: "I consent to being contacted regarding this enquiry.",
    privacyLink: "Privacy Policy",
    errName: "Please enter your full name.",
    errMobile: "Please enter a valid mobile number.",
    errEmail: "Please enter a valid email address.",
    errCity: "Please enter your city or area.",
    errSelect: "Please choose an option.",
    errMessage: "Please tell us a little about your enquiry.",
    errConsent: "Please provide consent to continue.",
    helperMobile: "We use this only to contact you about your registration.",
    helperEmail: "Optional. Useful if you prefer email contact.",
    demoNote: "This is a design preview. No information is submitted or stored.",
  },
  home: {
    title: "Maa Yashoda | Human Milk Bank Awareness & Outreach Initiative",
    heroEyebrow: "The Initiative",
    h1: "Maa Yashoda: A Journey of Care, Awareness and Connection",
    heroLead:
      "Breast milk is more than nutrition. Through breastfeeding awareness, safe donor human milk and community support, this initiative works to strengthen the Human Milk Bank and help vulnerable newborns receive the care and nourishment they need.",
    heroCollab: "In collaboration with Rotary organizations, healthcare institutions, partners and our community.",
    whyEyebrow: "Why It Matters",
    whyTitle: "Awareness is where every act of generosity begins",
    whyBody: [
      "Many mothers never learn that donor human milk exists, or that their own surplus milk could support a newborn in need. Awareness is the first and quietest part of this work.",
      "Connection is the second. A mother considering donation deserves a conversation rather than a form letter, someone who can explain the process, answer her questions and stay with her through it.",
      "Outreach carries both closer to the communities where mothers actually live, rather than waiting for them to find their way to a hospital. Together these form the foundation of a Human Milk Bank ecosystem that can grow over time.",
    ],
    whyQuote: "A mother's love can travel beyond her own home.",
    journeyEyebrow: "The Journey at a Glance",
    journeyTitle: "How the initiative connects",
    journeyNote:
      "Registering interest on this website begins a conversation. It does not confirm donor eligibility. That decision always rests with the authorized healthcare team.",
    journeySteps: ["Awareness", "Understanding", "Interest", "Appropriate Guidance", "Authorized Process"],
    vanEyebrow: "Human Milk Bank Van",
    vanTitle: "Taking awareness and connection closer to communities",
    vanBody:
      "Not every mother who wishes to learn about milk donation can easily travel to the Human Milk Bank. The Van is the outreach component of the initiative, carrying information, guidance and human contact into neighbourhoods, so that distance does not become a barrier to generosity.",
    vanPoints: [
      { t: "Community outreach", d: "Awareness reaches mothers where they are." },
      { t: "Donor guidance", d: "Questions answered in person, without pressure." },
      { t: "Connection", d: "A clear path between interested mothers and the Human Milk Bank." },
    ],
    grantEyebrow: "Grant Details",
    grantTitle: "A project with a purpose",
    grantBody:
      "The initiative has been made possible through collaboration between Rotary organizations, healthcare institutions, implementation partners, donors and the community under a Rotary Global Grant.",
    grantFocus:
      "The project focuses on Human Milk Bank upgradation, the Human Milk Bank Van, human milk collection support, breastfeeding awareness, identification and registration of potential donor mothers, and community outreach.",
    grantNumberLabel: "Rotary Global Grant",
    partnersEyebrow: "Partners",
    partnersTitle: "Together for every tiny life",
    partnersLead:
      "A collective effort bringing mothers, doctors, healthcare institutions, Rotary organizations, donors and communities together for vulnerable newborns.",
    galleryEyebrow: "Gallery",
    galleryTitle: "Moments from the initiative",
    galleryLead:
      "Illustrations celebrating awareness, community outreach, partnerships and the people behind the initiative.",
    statsEyebrow: "Impact",
    statsTitle: "The impact we create together",
    statsNote:
      "Figures shown are placeholders. All published statistics must be verified and dated before launch, and maintained through the content management system.",
    stats: [
      { v: "TBC", l: "Mothers reached through awareness" },
      { v: "TBC", l: "Mothers registered as interested" },
      { v: "TBC", l: "Communities reached" },
      { v: "TBC", l: "Awareness programmes held" },
    ],
    statsUpdated: "Last updated: to be confirmed",
    involvedEyebrow: "Ways to Get Involved",
    involvedTitle: "More than one way to make a difference",
    involved: [
      {
        t: "Become a Milk Donor",
        d: "Register your interest in learning more about the possibility of milk donation. No commitment is required at this stage.",
      },
      {
        t: "Support the Cause",
        d: "Individuals and organizations can help strengthen awareness, outreach and the Human Milk Bank ecosystem.",
      },
      {
        t: "Partner With the Initiative",
        d: "For companies, NGOs, institutions and community groups exploring structured collaboration.",
      },
    ],
    faqEyebrow: "Questions",
    faqTitle: "Answers before you ask",
    finalTitle: "Take the first step toward learning more",
    finalBody:
      "If you are curious about milk donation, you do not need to decide anything today. Register your interest and the appropriate team will guide you.",
  },
  about: {
    title: "About Maa Yashoda | The Project and Its Purpose",
    eyebrow: "About",
    h1: "About Maa Yashoda",
    lead: "Maa Yashoda is a breastfeeding awareness, human milk donation and Human Milk Bank outreach initiative based in Surat, supported by Rotary organizations, healthcare institutions, implementation partners and the community.",
    storyEyebrow: "The Story Behind the Initiative",
    storyTitle: "It began with a gap in awareness",
    storyBody: [
      "Human Milk Banks have existed within neonatal care for decades, yet most families have never heard of them. Mothers with surplus milk rarely know that a safe, guided pathway exists through which their generosity could support another family's newborn.",
      "The initiative was formed around that gap. Rather than beginning with infrastructure alone, it begins with awareness, with conversation, and with the trust required for a mother to consider donation at all.",
      "Alongside awareness, the project supports the upgradation of the Human Milk Bank and the introduction of a Human Milk Bank Van, so that outreach and institutional capacity grow together.",
    ],
    challengeEyebrow: "The Challenge",
    challengeTitle: "What stands in the way",
    challenges: [
      { t: "Limited awareness", d: "Breastfeeding support and donor human milk remain unfamiliar subjects for many families." },
      { t: "Distance", d: "Mothers willing to help may not be able to travel to a Human Milk Bank." },
      {
        t: "Uncertainty",
        d: "Without clear information, mothers hesitate, not because they are unwilling, but because no one has explained the process.",
      },
      { t: "Fragmented connection", d: "Interest expressed in a community rarely reaches the institution that can act on it." },
    ],
    approachEyebrow: "The Maa Yashoda Approach",
    approachTitle: "Five connected pillars",
    approach: [
      { t: "Awareness", d: "Clear, respectful information about breastfeeding and donor human milk." },
      { t: "Donor engagement", d: "A simple way for interested mothers to register and be guided." },
      { t: "Human Milk Bank ecosystem", d: "Support for the institutional capacity that makes donation possible." },
      { t: "Community outreach", d: "Presence in neighbourhoods, not only in hospitals." },
      { t: "Human Milk Bank Van", d: "Mobility that carries awareness and connection closer to mothers." },
    ],
    objEyebrow: "Project Objectives",
    objTitle: "What the project sets out to do",
    objNote: "Objectives are drawn from the project brief and remain subject to stakeholder review.",
    objectives: [
      "Strengthen and upgrade the Human Milk Bank.",
      "Introduce a Human Milk Bank Van for community outreach.",
      "Support safe and organized human milk collection.",
      "Build breastfeeding awareness among families.",
      "Identify and register potential donor mothers.",
      "Strengthen newborn and neonatal nutrition support.",
      "Extend outreach into communities across the project area.",
    ],
    grantEyebrow: "Rotary Global Grant",
    grantTitle: "Rotary Global Grant GG2694832",
    grantBody:
      "The project is supported by a Rotary Global Grant, which brings together host and international Rotary partners, The Rotary Foundation, healthcare institutions and implementation partners around a shared objective. The grant supports Human Milk Bank upgradation, the Human Milk Bank Van, collection support, awareness and outreach.",
    grantNote: "Detailed grant allocation figures are not published on this website.",
    ecoEyebrow: "The Ecosystem",
    ecoTitle: "No single organization does this alone",
    ecoBody:
      "The initiative works through four groups: Rotary organizations that convene and fund the project, healthcare institutions that hold clinical responsibility, implementation partners who carry out day-to-day work, and community stakeholders who make outreach possible.",
    visionEyebrow: "The Bigger Vision",
    visionTitle: "A model that can be repeated",
    visionBody:
      "The intention is to build something that continues after the grant period: an awareness culture around breastfeeding, a working connection between communities and the Human Milk Bank, and an outreach approach that other cities could adapt. Growth will follow what can be operationally sustained.",
    finalTitle: "Register your interest in milk donation",
    finalBody: "If the initiative resonates with you, the most valuable next step is a conversation.",
  },
  van: {
    title: "Human Milk Bank Van | Maa Yashoda",
    eyebrow: "Human Milk Bank Van",
    h1: "Taking Awareness and Connection Closer to Communities",
    lead: "The Human Milk Bank Van is an outreach component of the broader initiative. It carries information, guidance and human presence into communities, supporting the Human Milk Bank rather than replacing any part of it.",
    whyEyebrow: "Why the Van Matters",
    whyTitle: "Information rarely travels on its own",
    whyBody: [
      "Awareness campaigns reach the families who already read, search and attend. The mothers who most need a conversation about milk donation are often the ones least likely to encounter it.",
      "A physical presence changes that. When outreach arrives in a neighbourhood, questions get asked out loud, families join the conversation, and hesitation has somewhere to go.",
    ],
    quote: "When a mother is willing to share her gift of nourishment, distance should not become a barrier.",
    outreachEyebrow: "Taking Outreach Closer",
    outreachTitle: "What mobility makes possible",
    outreachPoints: [
      { t: "Presence", d: "Awareness activity in the places where mothers and families already gather." },
      { t: "Conversation", d: "Space to ask questions without an appointment or a hospital visit." },
      { t: "Continuity", d: "A recognizable point of contact that returns, rather than a one-time campaign." },
      { t: "Connection", d: "A route from community interest to the appropriate healthcare pathway." },
    ],
    outreachNote: "Service areas, routes and schedules will be published only once operationally confirmed.",
    roleEyebrow: "The Van's Role",
    roleTitle: "Two distinct components",
    roleBank: {
      t: "Human Milk Bank",
      d: "The healthcare and institutional component. Clinical processes, screening, handling and eligibility decisions sit here, under authorized healthcare professionals.",
    },
    roleVan: {
      t: "Human Milk Bank Van",
      d: "The outreach and connection component. Awareness, guidance, registration support and community engagement, as described by the approved project model.",
    },
    roleNote: "The Van does not independently perform clinical activities.",
    journeyEyebrow: "How the Journey Connects",
    journeyTitle: "From community to authorized process",
    journeySteps: ["Community", "Awareness", "Interest", "Appropriate Guidance", "Authorized Process"],
    repEyebrow: "What the Van Represents",
    repTitle: "Five ideas in motion",
    represents: ["Outreach", "Awareness", "Connection", "Accessibility", "Community engagement"],
    futureEyebrow: "Future Outreach",
    futureTitle: "Upcoming activity",
    futureBody: "Confirmed outreach events, locations and schedules will be published here as they are approved.",
    finalTitle: "Interested in milk donation?",
    finalBody: "Register your interest and the appropriate team will help you understand the next steps.",
  },
  partners: {
    title: "Our Partners | Maa Yashoda",
    eyebrow: "Partners",
    h1: "Together for a Shared Purpose",
    lead: "A collective effort bringing mothers, doctors, healthcare institutions, Rotary organizations, donors and communities together for vulnerable newborns.",
    ecoEyebrow: "Partnership Ecosystem",
    ecoTitle: "Four kinds of partnership",
    eco: [
      { t: "Rotary partners", d: "Clubs and districts that convene, fund and steward the project." },
      { t: "Healthcare and institutional partners", d: "Institutions that hold clinical and operational responsibility." },
      { t: "Implementation partners", d: "Teams carrying out day-to-day project work on the ground." },
      { t: "Community ecosystem", d: "Volunteers, community groups and supporters who make outreach possible." },
    ],
    rotaryTitle: "Rotary Partners",
    hostLabel: "Host Club",
    hostClub: "Rotary Club of Surat Riverside",
    participatingLabel: "Participating / Supporting Clubs",
    clubs: [
      "Rotary Club of Udhna",
      "Rotary Club of Tapi",
      "Rotary Club of Sachin",
      "Rotary Club of Surat Seaface",
      "Rotary Club of Shades Valley",
    ],
    districtsLabel: "Rotary Districts",
    districts: ["Rotary District 3060", "Rotary District 3142", "Rotary District 6860"],
    reservedLabel: "Reserved for confirmation",
    reserved: ["International Partner Rotary Club", "International Partner District", "The Rotary Foundation", "Additional Rotary Clubs"],
    healthTitle: "Healthcare and Institutional Partners",
    health: [
      { n: "Government Medical College, Surat", r: "Institutional Partner" },
      { n: "New Civil Hospital, Surat", r: "Healthcare Partner" },
      { n: "Department of Pediatrics, Government Medical College, Surat", r: "Clinical & Pediatric Partner" },
    ],
    assocTitle: "Implementation & Association Partners",
    assoc: [
      { n: "Chhayado", r: "Implementation & Operational Partner" },
      { n: "Surat Pediatric Association Charitable Trust", r: "Pediatric Association Partner" },
      { n: "Academy of Pediatrics, Gujarat", r: "State Pediatric Body" },
      { n: "Indian Academy of Pediatrics", r: "National Pediatric Body" },
    ],
    implTitle: "Implementation Partner",
    impl: { n: "Chhayado", r: "Implementation & Operational Partner" },
    approvalNote: "Organization names, roles, logos and brand usage are subject to confirmation and approval before publication.",
    grantTitle: "Global Grant Collaboration",
    grantBody:
      "This collaboration operates under Rotary Global Grant GG2694832, which brings host and international Rotary partners together with healthcare institutions and implementation partners.",
    flowEyebrow: "How Collaboration Creates Impact",
    flowTitle: "Shared vision to broader impact",
    flowSteps: ["Shared Vision", "Collective Resources", "Implementation", "Community Connection", "Broader Impact"],
    joinEyebrow: "Partner With the Initiative",
    joinTitle: "There is room for more collaboration",
    joinBody:
      "Companies, NGOs, institutions and community groups can explore collaboration across outreach, awareness, infrastructure, equipment and technology.",
    finalTitle: "Register your interest in milk donation",
    finalBody: "The most direct way to support this initiative is to learn more about donation.",
  },
  support: {
    title: "Support the Cause | Maa Yashoda",
    eyebrow: "Support",
    h1: "There Is More Than One Way to Make a Difference",
    lead: "Individuals and organizations can help strengthen awareness, outreach and the Human Milk Bank ecosystem that this initiative is built around.",
    whyEyebrow: "Why Support Matters",
    whyTitle: "What support makes possible",
    whyBody:
      "The journey of donor human milk requires awareness, safe collection, trained teams, transportation, storage, technology and continuous community outreach. Support helps strengthen this work and extend its reach.",
    areasEyebrow: "Areas of Impact",
    areasTitle: "Where support is directed",
    areas: [
      { t: "Human Milk Bank ecosystem", d: "Strengthening the institutional capacity behind safe donation." },
      { t: "Community outreach", d: "Presence and activity in the communities the project serves." },
      { t: "Awareness programmes", d: "Breastfeeding and donor milk education for families." },
      { t: "Mother engagement", d: "Guidance and support for mothers considering donation." },
      { t: "Equipment and resources", d: "The practical means outreach and collection depend on." },
      { t: "Technology", d: "Systems that keep registration, follow-up and records reliable." },
    ],
    waysEyebrow: "Ways to Support",
    waysTitle: "Four routes to involvement",
    ways: [
      { t: "Individual Support", d: "For individuals interested in approved contribution opportunities." },
      { t: "CSR Partnership", d: "For companies seeking structured impact opportunities." },
      { t: "Organizational Partnership", d: "For NGOs, institutions and foundations." },
      { t: "Community Support", d: "For awareness and outreach collaboration." },
    ],
    finEyebrow: "Financial Contributions",
    finTitle: "An enquiry-led approach for now",
    finBody:
      "Bank details, UPI IDs, QR codes and payment links are not published on this website. The official contribution pathway and governance process are being finalized. Until then, please send an enquiry and the appropriate team will respond with approved information.",
    csrEyebrow: "CSR and Organizational Partnership",
    csrTitle: "Collaboration, shaped together",
    csrBody:
      "Rather than fixed packages, collaboration areas are discussed with each organization: outreach, awareness, infrastructure, equipment, technology and sustainability initiatives. What is possible depends on the project's operational capacity at the time.",
    transEyebrow: "Transparency and Trust",
    transTitle: "Only what can be maintained",
    transBody:
      "This initiative publishes what it can verify and commits only to what it can operationally sustain. Grant information, partner recognition and statistics are reviewed before publication and updated as the project progresses.",
    formEyebrow: "Support / Partnership Enquiry",
    formTitle: "Start a conversation",
    formLead:
      "Tell us a little about how you would like to be involved. The relevant team will review the enquiry and connect with you regarding appropriate opportunities.",
    supportType: "Support Type",
    supportTypes: ["Individual Support", "CSR Partnership", "Organizational Partnership", "Community Collaboration", "Other"],
    areaOfInterest: "Area of Interest",
    nextEyebrow: "What Happens Next",
    nextSteps: ["Enquiry Received", "Review", "Appropriate Team Connection", "Explore Opportunities"],
    finalTitle: "The primary need remains milk donors",
    finalBody: "If you are a mother who may be able to donate, that is the most direct contribution of all.",
  },
  faqs: {
    title: "Frequently Asked Questions | Maa Yashoda",
    eyebrow: "FAQs",
    h1: "Frequently Asked Questions",
    lead: "Answers to the questions we are asked most often. Clinical and operational answers are reviewed by the appropriate teams before publication; where an answer awaits approval, that is stated plainly.",
    jump: "Jump to a category",
    groups: [
      {
        c: "About Maa Yashoda",
        q: [
          {
            q: "What is Maa Yashoda?",
            a: "Maa Yashoda is a breastfeeding awareness, human milk donation and Human Milk Bank outreach initiative based in Surat. It works to build awareness, connect interested mothers with the appropriate healthcare pathway, and support the Human Milk Bank through upgradation and community outreach.",
          },
          {
            q: "What is the purpose of the initiative?",
            a: "To make information about breastfeeding and donor human milk available to families, to give mothers who may be able to donate a clear and respectful route to guidance, and to strengthen the ecosystem that makes safe donation possible.",
          },
          {
            q: "Who is involved in the project?",
            a: "Rotary organizations, healthcare and institutional partners, an implementation partner and community stakeholders. The Partners page lists the organizations referenced in the project, subject to final confirmation.",
          },
          {
            q: "What is the Rotary Global Grant associated with the initiative?",
            a: "The project is supported by Rotary Global Grant GG2694832, which brings host and international Rotary partners together with healthcare institutions and implementation partners around a shared objective.",
          },
        ],
      },
      {
        c: "Becoming a Milk Donor",
        q: [
          {
            q: "Who can register their interest?",
            a: "Any mother who would like to learn more about the possibility of milk donation is welcome to register her interest. Registration is a request for information and guidance, not a clinical assessment.",
          },
          {
            q: "Does registering mean I am automatically eligible?",
            a: "No. Registering your interest does not confirm donor eligibility. Eligibility is determined only through the authorized healthcare process, by qualified professionals.",
          },
          {
            q: "Is registration voluntary?",
            a: "Entirely. Milk donation is a voluntary act of generosity, and you may stop at any point in the conversation.",
          },
          {
            q: "Do I need to make a decision immediately?",
            a: "No. Many mothers register simply to understand the process. You are free to ask questions and decide later, or not at all.",
          },
          {
            q: "Can I learn more before proceeding?",
            a: "Yes. You can read the About the Project and Milk Bank Van pages, or contact the team with questions before registering.",
          },
        ],
      },
      {
        c: "Registration and Next Steps",
        q: [
          {
            q: "What happens after I register?",
            a: "Your registration enters the approved project communication workflow. The appropriate team may review it and provide further guidance. Any further assessment follows the applicable authorized pathway.",
          },
          {
            q: "What information do I need to provide?",
            a: "Only basic details: your name, mobile number, city or area, and what kind of guidance you are looking for. The public form does not ask for medical history.",
          },
          {
            q: "How will I be contacted?",
            a: "Through the contact method you choose on the form, from among the channels the team actively monitors.",
          },
          {
            q: "Can I contact the team with questions first?",
            a: "Yes. The Contact page provides a general enquiry route for questions before registration.",
          },
        ],
      },
      {
        c: "Understanding the Process",
        q: [
          {
            q: "What is donor human milk?",
            a: "Donor human milk is breast milk provided by a screened donor mother through an authorized Human Milk Bank process, for use where it is clinically appropriate. Detailed clinical wording for this answer is pending healthcare approval.",
          },
          {
            q: "How does the authorized process work?",
            a: "The process is defined and operated by the authorized Human Milk Bank healthcare team. A public description of the steps will be published once approved by the relevant healthcare authorities.",
          },
          {
            q: "How is eligibility determined?",
            a: "Eligibility is determined by authorized healthcare professionals according to institutional protocols. This website does not assess or decide eligibility.",
          },
          {
            q: "How is donated milk handled?",
            a: "Donated milk is handled according to the approved Human Milk Bank protocols of the relevant healthcare institution. Detailed handling information is pending healthcare approval.",
          },
        ],
      },
      {
        c: "Human Milk Bank",
        q: [
          {
            q: "What is a Human Milk Bank?",
            a: "A Human Milk Bank is a healthcare facility that collects, screens, processes and stores donated human milk for use where clinically appropriate, operating under institutional protocols.",
          },
          {
            q: "What is its role in the initiative?",
            a: "The Human Milk Bank is the healthcare and institutional centre of the initiative. Awareness and outreach activity exists to support it, not to substitute for it.",
          },
          {
            q: "Who operates the relevant healthcare processes?",
            a: "Authorized healthcare professionals at the relevant institution. The project's awareness and outreach team does not perform clinical activities.",
          },
        ],
      },
      {
        c: "Human Milk Bank Van",
        q: [
          {
            q: "What is the Milk Bank Van?",
            a: "The Human Milk Bank Van is the outreach component of the initiative. It carries awareness, information and guidance into communities and connects interested mothers with the appropriate pathway.",
          },
          {
            q: "Why is it important?",
            a: "Because distance and unfamiliarity keep willing mothers from ever reaching a Human Milk Bank. Outreach closes that gap by arriving where mothers already are.",
          },
          {
            q: "Does it replace the Human Milk Bank?",
            a: "No. The Van supports outreach and connection. Clinical processes remain with the Human Milk Bank and its authorized healthcare team.",
          },
          {
            q: "How does outreach connect with the broader process?",
            a: "Community awareness leads to interest, interest leads to appropriate guidance, and guidance connects a mother to the authorized process where applicable.",
          },
        ],
      },
      {
        c: "Supporting the Initiative",
        q: [
          {
            q: "How can I support Maa Yashoda?",
            a: "Through awareness, community collaboration or approved contribution opportunities. The Support the Cause page describes the available routes and provides an enquiry form.",
          },
          {
            q: "Can my organization explore CSR opportunities?",
            a: "Yes. Send a support enquiry describing your area of interest and the relevant team will respond regarding appropriate opportunities.",
          },
          {
            q: "Can organizations become partners?",
            a: "Partnership is possible across outreach, awareness, infrastructure, equipment, technology and sustainability initiatives, subject to project capacity and approval.",
          },
          {
            q: "How can I contact the team?",
            a: "Use the general enquiry form on the Contact page. Approved and actively monitored contact channels are published there.",
          },
        ],
      },
    ],
    finalTitle: "Still have a question?",
    finalBody: "If your question is not answered here, the team is glad to hear from you.",
  },
  donor: {
    title: "Become a Milk Donor | Maa Yashoda",
    eyebrow: "Register Your Interest",
    h1: "Register Your Interest in Becoming a Milk Donor",
    lead: "If you are interested in learning more about the possibility of milk donation, you can register your interest here. Only basic information is requested, so that the appropriate team can follow up with guidance.",
    reassurance: "Registering your interest does not automatically confirm donor eligibility.",
    whoTitle: "Who is this for?",
    whoBody: "You may wish to register if:",
    who: [
      "You are currently breastfeeding and interested in learning more.",
      "You believe you may have surplus breast milk.",
      "You would like guidance before making any decision.",
    ],
    whoNote: "These are not eligibility rules. They are simply common reasons mothers get in touch.",
    nextTitle: "What happens next?",
    next: [
      { t: "You register your interest", d: "A short form, no medical questions." },
      { t: "Your registration enters the approved workflow", d: "It reaches the project's communication process." },
      { t: "The appropriate team provides guidance", d: "Someone gets in touch through your preferred channel." },
      { t: "Any further process follows the authorized pathway", d: "Assessment, if any, rests with authorized healthcare professionals." },
    ],
    formTitle: "Registration Form",
    formLead: "Only basic information is requested, to understand your interest and enable appropriate follow-up.",
    secBasic: "Basic Information",
    secLocation: "Location",
    secInterest: "Your Interest",
    secContact: "Preferred Contact Method",
    secMessage: "Additional Message",
    secConsent: "Consent",
    privacyTitle: "Privacy and data handling",
    privacyBody:
      "The information you provide is collected to understand your interest and to enable appropriate follow-up through the approved project communication workflow. It is not used to assess eligibility. You can read how information is handled in the Privacy Policy.",
    faqTitle: "Before you register",
    finalTitle: "Thank you for considering this",
    finalBody: "Every mother's journey is different. Whatever you decide, learning more costs nothing and helps no one less.",
  },
  contact: {
    title: "Contact Maa Yashoda | Project Enquiries and Partnerships",
    eyebrow: "Contact",
    h1: "Let's Start a Conversation",
    lead: "Questions about Maa Yashoda, the Human Milk Bank Van, partnerships, CSR or support are all welcome here.",
    routeEyebrow: "Choose How We Can Help",
    routeTitle: "Four common routes",
    routes: [
      { t: "Interested in milk donation", d: "Register your interest and the appropriate team will guide you.", cta: "Become a Milk Donor" },
      { t: "General question", d: "Ask us anything about the project or the initiative.", cta: "Go to enquiry form" },
      { t: "Want to partner", d: "For companies, NGOs, institutions and community groups.", cta: "Explore Partnership Opportunities" },
      { t: "Want to support", d: "Explore the ways individuals and organizations can help.", cta: "Support the Cause" },
    ],
    optionsTitle: "Contact options",
    optionsNote: "Approved and actively monitored contact channels will be published here before launch.",
    options: [
      { t: "Phone", d: "To be confirmed" },
      { t: "Email", d: "drprashantkariya@gmail.com" },
      { t: "Location", d: "Surat, Gujarat, India" },
    ],
    primaryContactLabel: "Primary Project Contact",
    primaryContactName: "Dr. Prashant Kariya",
    primaryContactEmail: "drprashantkariya@gmail.com",
    primaryContactNote: "For project, partnership and CSR enquiries.",
    formEyebrow: "General Enquiry",
    formTitle: "Send us an enquiry",
    category: "Enquiry Category",
    categories: ["About Maa Yashoda", "Human Milk Bank Van", "Partnership", "CSR", "Supporting the Cause", "Media / Communication", "Other"],
    projectTitle: "Project information",
    projectLinks: "Quick links",
    faqTitle: "Your question may already be answered",
    faqBody: "The FAQ page covers the initiative, registration, the process, the Human Milk Bank and the Van.",
    finalTitle: "Interested in milk donation?",
    finalBody: "Registering your interest is the quickest way to reach the right team.",
  },
  privacy: {
    title: "Privacy Policy | Maa Yashoda",
    h1: "Privacy Policy",
    updated: "Last updated: to be confirmed before launch",
    note: "This policy is a working draft. Legal and operational review is required before publication.",
    toc: "On this page",
    sections: [
      {
        h: "Introduction",
        p: [
          "This policy explains how information submitted through the Maa Yashoda website is collected, used and handled. It applies to the public website and the forms published on it.",
        ],
      },
      {
        h: "Information We Collect",
        p: [
          "Through the forms on this website we may collect: name, mobile number, email address, city or area, organization information, enquiry content and information about your interest in milk donation.",
          "The published list will be finalized to match exactly the fields present on the live website.",
        ],
      },
      {
        h: "How We Use Information",
        p: [
          "Information is used to respond to enquiries, to communicate about donor interest registration, to support approved next-step communication, to respond to partnership enquiries, to maintain security and to improve website operations.",
        ],
      },
      {
        h: "Milk Donor Registration Information",
        p: [
          "The donor form on this website records interest only. It does not replace an authorized medical, screening or eligibility process, and it is not used to make eligibility decisions.",
        ],
      },
      {
        h: "Information Sharing",
        p: [
          "Information may be shared with authorized project team members, relevant implementation personnel and authorized institutional pathways, and with technology providers acting on the project's behalf. The final list of recipient categories will reflect actual practice.",
        ],
      },
      {
        h: "Data Storage and Security",
        p: [
          "Reasonable technical and organizational safeguards are applied, including restricted access and secure transmission. No method of transmission or storage can be guaranteed to be completely secure.",
        ],
      },
      {
        h: "Cookies and Analytics",
        p: [
          "Analytics and cookie usage will be disclosed here once the final tooling is confirmed. Tracking will not include names, phone numbers, email addresses or health information.",
        ],
      },
      { h: "Data Retention", p: ["Retention periods, or the criteria used to determine them, will be defined by the project before launch and stated here."] },
      {
        h: "Rights and Choices",
        p: [
          "You may request correction of your information, withdraw consent to further communication, or make a data-related request through the contact route published on this website, subject to applicable legal and operational requirements.",
        ],
      },
      {
        h: "Third-Party Services",
        p: ["Categories of third-party services used by the website, such as hosting, form handling and analytics, will be listed here once confirmed."],
      },
      { h: "Children's Privacy", p: ["The website is intended for adults. Wording here will reflect the actual service and applicable law following legal review."] },
      { h: "Policy Changes", p: ["Changes to this policy will be published on this page with an updated revision date."] },
      { h: "Contact", p: ["Privacy-related contact information will be published here once approved."] },
    ],
  },
  terms: {
    title: "Terms of Use | Maa Yashoda",
    h1: "Terms of Use",
    updated: "Last updated: to be confirmed before launch",
    note: "This document is a working draft. Legal review is required before publication.",
    toc: "On this page",
    sections: [
      { h: "Acceptance of Terms", p: ["By using this website you agree to these terms. If you do not agree, please do not use the website."] },
      {
        h: "Website Purpose",
        p: [
          "This website provides general information about the Maa Yashoda initiative and allows visitors to register interest in learning more about milk donation, or to send an enquiry.",
        ],
      },
      { h: "Information Accuracy", p: ["Content is provided in good faith and reviewed before publication. Some information is subject to ongoing approval and may change."] },
      {
        h: "No Medical Advice",
        p: [
          "Website content is intended for general awareness and communication and is not a substitute for professional medical advice. Please consult a qualified healthcare professional for medical guidance.",
        ],
      },
      {
        h: "Donor Interest Registration",
        p: [
          "Registration of interest does not automatically confirm donor eligibility. Eligibility is determined solely by authorized healthcare professionals through the applicable authorized process.",
        ],
      },
      { h: "Intellectual Property", p: ["Website content, marks and partner logos remain the property of their respective owners and may not be reused without permission."] },
      { h: "Acceptable Use", p: ["Do not misuse the website, submit false information, attempt unauthorized access, or use automated means to submit forms."] },
      { h: "Third-Party Links", p: ["The website may link to third-party sites. Their content and practices are not under this project's control."] },
      {
        h: "Limitation of Liability",
        p: ["To the extent permitted by applicable law, the project and its partners are not liable for indirect or consequential loss arising from use of this website."],
      },
      { h: "Changes", p: ["These terms may be updated. The revision date above indicates the current version."] },
      { h: "Governing Law", p: ["These terms are governed by the applicable laws of India, subject to legal review."] },
      { h: "Contact", p: ["Questions about these terms can be sent through the contact route published on this website."] },
    ],
  },
  accessibility: {
    title: "Accessibility Statement | Maa Yashoda",
    h1: "Accessibility Statement",
    updated: "Last updated: to be confirmed before launch",
    note: "",
    toc: "On this page",
    sections: [
      {
        h: "Our Intention",
        p: ["This website aims to be usable by as many visitors as reasonably possible, including people using assistive technology, keyboard navigation or smaller screens."],
      },
      {
        h: "What We Work On",
        p: ["Keyboard navigation, screen-reader compatibility, clear document structure, adequate colour contrast, responsive layouts, readable typography and accessible forms."],
      },
      { h: "Known Limitations", p: ["Some content awaits approval and may be updated. Where limitations are identified, they will be listed here along with planned improvements."] },
      {
        h: "Reporting an Issue",
        p: [
          "If you encounter a barrier on this website, please tell us through the contact route published on this website and we will look into it. An approved accessibility contact will be published before launch.",
        ],
      },
    ],
  },
  thanks: {
    donor: {
      title: "Thank You | Maa Yashoda",
      h1: "Thank You for Taking the First Step",
      lead: "Your registration of interest has been received.",
      steps: [
        "Your registration has entered the approved project communication workflow.",
        "The appropriate team may review it.",
        "Further guidance follows the established process.",
      ],
      note: "Registration does not automatically confirm donor eligibility.",
      linksTitle: "While you wait",
      links: [
        { t: "About the Project", p: "about" },
        { t: "Frequently Asked Questions", p: "faqs" },
        { t: "Milk Bank Van", p: "van" },
      ],
    },
    contact: {
      title: "Thank You | Maa Yashoda",
      h1: "Thank You for Contacting Us",
      lead: "Your enquiry has been received. The appropriate team will review it and respond through the channel you selected.",
      steps: [],
      note: "",
      linksTitle: "In the meantime",
      links: [
        { t: "About the Project", p: "about" },
        { t: "Frequently Asked Questions", p: "faqs" },
        { t: "Support the Cause", p: "support" },
      ],
    },
    support: {
      title: "Thank You | Maa Yashoda",
      h1: "Thank You for Your Interest in Supporting Maa Yashoda",
      lead: "Your enquiry has been received. The relevant team can review it and connect with you regarding appropriate opportunities.",
      steps: [],
      note: "",
      linksTitle: "Learn more",
      links: [
        { t: "About the Project", p: "about" },
        { t: "Our Partners", p: "partners" },
        { t: "Milk Bank Van", p: "van" },
      ],
    },
  },
  notFound: {
    title: "Page Not Found | Maa Yashoda",
    h1: "This Page Seems to Have Taken a Different Route",
    lead: "The page may have moved, changed or may no longer be available.",
    linksTitle: "Helpful links",
    links: [
      { t: "Become a Milk Donor", p: "donor" },
      { t: "About the Project", p: "about" },
      { t: "Milk Bank Van", p: "van" },
      { t: "FAQs", p: "faqs" },
    ],
  },
};

export type Content = typeof en;
export default en;
